language: python

# needed to use trusty
sudo: required

dist: trusty

python:
  - "3.5"
  - "3.6"
  - "pypy-5.3.1"

install:
  - pip install coveralls
  - pip install codecov
  - python setup.py install

script:
  - coverage run --source=nand2vm setup.py test

after_success:
  - coveralls
  - codecov

